version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/track-my-warranties
      - NO_RESPONSE_EMAIL=noresponse@email.com
      - ADMIN_EMAIL=admin@email.com
      - PROD_URL=http://localhost:3000
      - SECRET=thisIsNotAGoodSecret
      - TZ=Pacific/Auckland
      # - SENDGRID_API_KEY=defined in .github/workflows/ci.yml
      # - S3_ACCESS_KEY=defined in .github/workflows/ci.yml
      # - S3_ACCESS_SECRET=defined in .github/workflows/ci.yml
      - S3_BUCKET=track-my-warranties-dev
    depends_on:
      - mongodb
  cypress:
    image: cypress/included:10.1.0
    container_name: cypress
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
    entrypoint: ["sleep", "infinity"]
volumes:
  mongodata:
  s3mockdata:
