version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/track-my-warranties
      - NO_RESPONSE_EMAIL=noresponse@email.com
      - ADMIN_EMAIL=admin@email.com
      - PROD_URL=http://localhost:3000
      - SECRET=thisIsNotAGoodSecret
      - TZ=Pacific/Auckland
      - S3_ACCESS_KEY=minioadmin
      - S3_ACCESS_SECRET=minioadmin
      - S3_BUCKET=track-my-warranties-dev
      - S3MOCK_PORT=9000
    depends_on:
      - mongodb
      - createbucket
  s3mock:
    image: minio/minio:latest
    container_name: s3mock
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3mockdata:/data
    command: ["server", "--console-address", ":9001", "/data"]
  createbucket:
    image: minio/mc
    container_name: createbucket
    depends_on:
      - s3mock
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3mock http://s3mock:9000 minioadmin minioadmin;
      /usr/bin/mc mb s3mock/track-my-warranties-dev;
      exit 0;
      "
  cypress:
    image: cypress/included:10.1.0
    container_name: cypress
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
    # entrypoint: ["sleep","infinity"]
volumes:
  mongodata:
  s3mockdata:
