name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build docker
        run: npm run updev
      - name: Run tests
        run: npm test
      - name: Deploy to Heroku
        run: echo "TODO"