name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build docker
        run: docker-compose -f docker-compose-test.yml up --build -d
      - name: Run tests
        run: docker exec cypress cypress run
      - name: Deploy to Heroku
        run: echo "TODO"